export enum ErrorMessage {
    INVALID_IDENTIFIER_OR_USER_NOT_FOUND = "Invaild identifier.",
    PASSWORD_INCORRECT = "Password incorrect.",
    INTERNAL_SERVER_ERROR = "Internal Server Error.",
    USERNAME_ALREADY_TAKEN = "Username already taken.",
    EMAIL_ALREADY_TAKEN = "Email already taken.",
    PHONENUMBER_ALREADY_TAKEN = "Phonenumber already taken.",
    NOT_AUTHENTICATED = "Not authenticated.",
    TOKEN_EXPIRED = "Token expired.",
    REQUIRED_CREDENTIALS_NOT_GIVEN = "Provide all required details.",
    INVALID_USER = "Invalid User",
    CHAT_NOT_FOUND = "Start or create new chat. Chat",
    INVALID_CHAT = "Invalid Chat",
    INVALID_MESSAGE = "Invalid Message",
}